"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { encodeFunctionData, parseAbi, type PublicClient, type TransactionReceipt } from "viem";
import { useAccount, usePublicClient, useWalletClient } from "wagmi";
import { EXAMPLE_TARGET_ADDRESS } from "~~/utils/gasless/config";
import { signMetaTransaction, signMetaTransactionWithNonce } from "~~/utils/gasless/metaTx";
import { getNonce, relayBatchTransactions, relayTransaction } from "~~/utils/gasless/relayerClient";
import { ForwardRequest } from "~~/utils/gasless/types";

export type ActionId = "direct" | "gasless" | "batch";

// A stable, monotonically-keyed log entry. React keys must be stable
// across renders to avoid spurious unmounts/remounts; using the array
// index as a key breaks when entries are filtered or trimmed. The id is
// generated by an in-hook counter (see `nextLogIdRef` below).
export interface LogEntry {
  id: number;
  text: string;
}

// Type-safe extraction of a user-visible message from a thrown value.
// catch (error: any) bypasses TS narrowing and produces "undefined" for
// non-Error throws (e.g. `throw "boom"`); this helper preserves the
// message for Error subclasses (including viem's BaseError, which sets
// `.shortMessage`) and falls back to String(value) for everything else.
function errorMessage(err: unknown): string {
  if (err instanceof Error) {
    // viem error subclasses expose a friendlier `shortMessage` field.
    const short = (err as { shortMessage?: unknown }).shortMessage;
    if (typeof short === "string" && short.length > 0) return short;
    return err.message;
  }
  if (typeof err === "string") return err;
  try {
    return JSON.stringify(err);
  } catch {
    return String(err);
  }
}

export const exampleTargetAbi = parseAbi([
  "function addPoints(uint256 amount) public",
  "function getPoints(address user) public view returns (uint256)",
]);

// Poll a tx hash until a receipt is observed or maxAttempts elapse.
async function pollForTransactionReceipt({
  txHash,
  publicClient,
  addLog,
  maxAttempts = 60,
  onSuccess,
  onReverted,
  onUnknown,
}: {
  txHash: `0x${string}`;
  publicClient: PublicClient;
  addLog: (message: string) => void;
  maxAttempts?: number;
  onSuccess: (receipt: TransactionReceipt) => Promise<void>;
  onReverted: () => void;
  onUnknown: (receipt: TransactionReceipt) => Promise<void>;
}): Promise<boolean> {
  // Errors during polling are usually benign — viem's getTransactionReceipt
  // throws "Transaction receipt with hash ... could not be found" while the
  // tx is still pending, on every attempt. Surfacing those would flood the
  // log. Suppress them by default but emit a sample (every 5th attempt) so
  // an operator watching a genuinely stuck poll can still see RPC errors,
  // schema mismatches, or network blips.
  const ERROR_SAMPLE_INTERVAL = 5;
  let attempts = 0;
  let lastErrorMessage: string | undefined;
  let suppressedErrorCount = 0;

  while (attempts < maxAttempts) {
    attempts++;
    try {
      const receipt = await publicClient.getTransactionReceipt({ hash: txHash });
      addLog(`📋 Receipt found! Status: ${receipt.status}`);
      if (receipt.status === "success") {
        await onSuccess(receipt);
        return true;
      } else if (receipt.status === "reverted") {
        onReverted();
        return true;
      } else {
        addLog(`⚠️ Unknown receipt status: ${receipt.status}`);
        await onUnknown(receipt);
        return true;
      }
    } catch (err: unknown) {
      // Track the most recent error so the periodic sample reflects what's
      // actually going wrong right now rather than the very first error.
      lastErrorMessage = errorMessage(err);
      suppressedErrorCount++;
      if (attempts % ERROR_SAMPLE_INTERVAL === 0) {
        addLog(
          `⚠️  Polling error (${suppressedErrorCount} since last report, attempt ${attempts}/${maxAttempts}): ${lastErrorMessage}`,
        );
        suppressedErrorCount = 0;
      }
    }
    if (attempts % 5 === 0) {
      addLog(`⏳ Still waiting... (${attempts}s elapsed)`);
    }
    await new Promise(resolve => setTimeout(resolve, 1000));
  }

  // On timeout, surface the last seen error (if any) so the user has a
  // concrete failure mode to investigate, not just "timeout".
  if (lastErrorMessage) {
    addLog(`⚠️  Final polling error before timeout: ${lastErrorMessage}`);
  }
  return false;
}

export interface UseGaslessDemo {
  // Points
  points: bigint;
  loadingPoints: boolean;
  loadPoints: () => Promise<void>;
  // Logs / tx
  logs: LogEntry[];
  txHash: string;
  clearLogs: () => void;
  // Per-action state
  isRunning: (id: ActionId) => boolean;
  // Actions
  handleDirectCall: () => Promise<void>;
  handleGaslessCall: () => Promise<void>;
  handleBatchCall: () => Promise<void>;
}

export function useGaslessDemo(): UseGaslessDemo {
  const { address, isConnected } = useAccount();
  const publicClient = usePublicClient();
  const { data: walletClient } = useWalletClient();

  const [points, setPoints] = useState<bigint>(0n);
  const [loadingPoints, setLoadingPoints] = useState(false);
  // Per-action loading state. A Set lets the three demo actions run
  // concurrently so users can compare Direct, Gasless, and Batch flows
  // side-by-side without one button blocking the others.
  const [runningActions, setRunningActions] = useState<Set<ActionId>>(new Set());
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [txHash, setTxHash] = useState<string>("");
  const activeTimers = useRef<NodeJS.Timeout[]>([]);
  // Monotonically increasing log id. Survives filter changes, clears, and
  // re-renders so each entry has a permanently unique React key.
  const nextLogIdRef = useRef(0);

  const startAction = useCallback((id: ActionId) => {
    // Clear any stale tx hash from the previous action so the "Latest
    // Transaction Hash" panel doesn't display a hash that belongs to a
    // different (already-completed) transaction while this one is still
    // running. The handler will populate it again once it has a fresh
    // hash from the wallet or relayer.
    setTxHash("");
    setRunningActions(prev => {
      const next = new Set(prev);
      next.add(id);
      return next;
    });
  }, []);

  const finishAction = useCallback((id: ActionId) => {
    setRunningActions(prev => {
      if (!prev.has(id)) return prev;
      const next = new Set(prev);
      next.delete(id);
      return next;
    });
  }, []);

  const isRunning = useCallback((id: ActionId) => runningActions.has(id), [runningActions]);

  const addLog = useCallback((message: string) => {
    const id = nextLogIdRef.current++;
    const text = `[${new Date().toLocaleTimeString()}] ${message}`;
    setLogs(prev => [...prev, { id, text }]);
  }, []);

  // Educational demo: surface the exact EIP-712 message contents to the
  // on-page log so users can see what they're authorising before the
  // wallet prompt appears.
  const logEip712Payload = useCallback(
    (
      label: string,
      request: ForwardRequest,
      decoded: { functionName: string; args: readonly unknown[] },
      nonce?: bigint,
    ) => {
      const argsPretty = decoded.args.map(a => (typeof a === "bigint" ? a.toString() : String(a))).join(", ");
      const deadlineNum = Number(request.deadline);
      const deadlineIso = Number.isFinite(deadlineNum)
        ? new Date(deadlineNum * 1000).toISOString()
        : request.deadline;
      addLog(`🔎 ${label} — about to sign EIP-712 ForwardRequest:`);
      addLog(`     • call:     ${decoded.functionName}(${argsPretty})`);
      addLog(`     • from:     ${request.from}`);
      addLog(`     • to:       ${request.to}`);
      addLog(`     • value:    ${request.value} wei`);
      addLog(`     • gas:      ${request.gas}`);
      addLog(`     • deadline: ${request.deadline} (${deadlineIso})`);
      if (nonce !== undefined) {
        addLog(`     • nonce:    ${nonce.toString()}`);
      }
      addLog(`     • data:     ${request.data}`);
    },
    [addLog],
  );

  const addTimer = useCallback((callback: () => void, delay: number) => {
    const timer = setTimeout(callback, delay);
    activeTimers.current.push(timer);
    return timer;
  }, []);

  const loadPoints = useCallback(async () => {
    if (!address || !publicClient) return;
    if (!EXAMPLE_TARGET_ADDRESS) return;
    setLoadingPoints(true);
    try {
      const result = await publicClient.readContract({
        address: EXAMPLE_TARGET_ADDRESS,
        abi: exampleTargetAbi,
        functionName: "getPoints",
        args: [address],
      });
      setPoints(result as bigint);
    } catch (error) {
      console.error("Failed to load points:", error);
      addLog("❌ Failed to load points");
    } finally {
      setLoadingPoints(false);
    }
  }, [address, publicClient, addLog]);

  // Auto-load points on connect; reset on disconnect.
  useEffect(() => {
    if (isConnected && address) {
      loadPoints();
    } else if (!isConnected) {
      setPoints(0n);
      setLogs([]);
      setTxHash("");
    }
  }, [address, isConnected, loadPoints]);

  // Cleanup any pending timers on unmount.
  useEffect(() => {
    return () => {
      activeTimers.current.forEach(timer => clearTimeout(timer));
      activeTimers.current = [];
    };
  }, []);

  const handleDirectCall = useCallback(async () => {
    if (!address || !walletClient) {
      addLog("❌ Please connect your wallet");
      return;
    }
    if (!EXAMPLE_TARGET_ADDRESS) {
      addLog("❌ EXAMPLE_TARGET_ADDRESS is not configured (set NEXT_PUBLIC_EXAMPLE_TARGET_ADDRESS).");
      return;
    }
    startAction("direct");
    try {
      addLog("📝 Preparing direct transaction...");
      const hash = await walletClient.writeContract({
        address: EXAMPLE_TARGET_ADDRESS,
        abi: exampleTargetAbi,
        functionName: "addPoints",
        args: [10n],
        account: address,
      });
      addLog(`✅ Transaction sent: ${hash}`);
      setTxHash(hash);
      addLog("⏳ Waiting for confirmation...");
      if (publicClient) {
        await publicClient.waitForTransactionReceipt({ hash });
        addLog("✅ Transaction confirmed!");
        await loadPoints();
      }
    } catch (error: unknown) {
      addLog(`❌ Error: ${errorMessage(error)}`);
    } finally {
      finishAction("direct");
    }
  }, [address, walletClient, publicClient, addLog, startAction, finishAction, loadPoints]);

  const handleGaslessCall = useCallback(async () => {
    if (!address || !walletClient) {
      addLog("❌ Please connect your wallet");
      return;
    }
    if (!EXAMPLE_TARGET_ADDRESS) {
      addLog("❌ EXAMPLE_TARGET_ADDRESS is not configured (set NEXT_PUBLIC_EXAMPLE_TARGET_ADDRESS).");
      return;
    }
    startAction("gasless");
    try {
      addLog("📝 Encoding function data...");
      const data = encodeFunctionData({
        abi: exampleTargetAbi,
        functionName: "addPoints",
        args: [10n],
      });
      const deadline = Math.floor(Date.now() / 1000) + 3600;
      const request: ForwardRequest = {
        from: address,
        to: EXAMPLE_TARGET_ADDRESS,
        value: "0",
        gas: "200000",
        deadline: deadline.toString(),
        data,
      };

      logEip712Payload("Single gasless", request, { functionName: "addPoints", args: [10n] });
      addLog("✍️  Signing EIP-712 message (fetching nonce internally)...");
      const signature = await signMetaTransaction(walletClient, request);
      addLog("✅ Signature obtained");

      addLog("📡 Sending to relayer...");
      const response = await relayTransaction({ request, signature });

      if (response.success && response.txHash) {
        addLog(`✅ Relayer submitted tx: ${response.txHash}`);
        setTxHash(response.txHash);
        addLog("⏳ Waiting for confirmation...");
        if (publicClient) {
          const confirmed = await pollForTransactionReceipt({
            txHash: response.txHash as `0x${string}`,
            publicClient,
            addLog,
            onSuccess: async receipt => {
              addLog(`✅ Transaction confirmed in block ${receipt.blockNumber}!`);
              await loadPoints();
            },
            onReverted: () => addLog("❌ Transaction reverted on-chain"),
            onUnknown: async receipt => {
              addLog(`⚠️ Unknown receipt status: ${receipt.status}`);
              await loadPoints();
            },
          });
          if (!confirmed) {
            addLog("⚠️ Confirmation timeout - transaction may still be processing");
            addLog(`Check: https://explorer.testnet.rootstock.io/tx/${response.txHash}`);
            addTimer(() => loadPoints(), 3000);
          }
        }
      } else {
        addLog(`❌ Relayer error: ${response.error}`);
      }
    } catch (error: unknown) {
      addLog(`❌ Error: ${errorMessage(error)}`);
    } finally {
      finishAction("gasless");
    }
  }, [address, walletClient, publicClient, addLog, addTimer, logEip712Payload, startAction, finishAction, loadPoints]);

  const handleBatchCall = useCallback(async () => {
    if (!address || !walletClient) {
      addLog("❌ Please connect your wallet");
      return;
    }

    const amounts = [5, 10, 15];

    // Up-front user consent: this action requires N separate wallet
    // signature prompts. Without this confirmation, users see prompts 2
    // and 3 with no context and dismissals only surface as a log line.
    const confirmed = window.confirm(
      `Batch gasless transaction\n\n` +
        `You will be prompted to sign ${amounts.length} separate messages — one per transaction.\n` +
        `Please approve ALL ${amounts.length} prompts. Dismissing any prompt will abort the batch.\n\n` +
        `Continue?`,
    );
    if (!confirmed) {
      addLog("ℹ️  Batch cancelled before signing.");
      return;
    }

    if (!EXAMPLE_TARGET_ADDRESS) {
      addLog("❌ EXAMPLE_TARGET_ADDRESS is not configured (set NEXT_PUBLIC_EXAMPLE_TARGET_ADDRESS).");
      return;
    }
    startAction("batch");
    try {
      addLog(`📦 Preparing batch of ${amounts.length} transactions...`);
      addLog(`✍️  You will be prompted to sign ${amounts.length} messages — please approve all ${amounts.length}.`);

      const requests: Array<{ request: ForwardRequest; signature: string }> = [];

      addLog("🔍 Fetching starting nonce...");
      const currentNonce = await getNonce(address);
      addLog(`✅ Starting nonce: ${currentNonce}`);

      for (let i = 0; i < amounts.length; i++) {
        const amount = amounts[i];
        addLog(`📝 Preparing transaction ${i + 1}: addPoints(${amount}) with nonce ${currentNonce + BigInt(i)}...`);

        const data = encodeFunctionData({
          abi: exampleTargetAbi,
          functionName: "addPoints",
          args: [BigInt(amount)],
        });
        const deadline = Math.floor(Date.now() / 1000) + 3600;
        const request: ForwardRequest = {
          from: address,
          to: EXAMPLE_TARGET_ADDRESS,
          value: "0",
          gas: "200000",
          deadline: deadline.toString(),
          data,
        };

        const nonceForThis = currentNonce + BigInt(i);
        logEip712Payload(
          `Batch transaction ${i + 1}/${amounts.length}`,
          request,
          { functionName: "addPoints", args: [BigInt(amount)] },
          nonceForThis,
        );
        addLog(`✍️  Signing transaction ${i + 1}...`);
        const signature = await signMetaTransactionWithNonce(walletClient, request, nonceForThis);
        requests.push({ request, signature });
      }

      addLog(`✅ All ${amounts.length} transactions signed with sequential nonces!`);
      addLog("📡 Sending batch to relayer...");
      const response = await relayBatchTransactions(requests);

      if (response.success && response.txHash) {
        addLog(`✅ Batch submitted in single tx: ${response.txHash}`);
        addLog(`💰 Gas savings: ~35% compared to ${amounts.length} separate transactions!`);
        setTxHash(response.txHash);
        addLog("⏳ Waiting for confirmation...");
        if (publicClient) {
          const confirmed2 = await pollForTransactionReceipt({
            txHash: response.txHash as `0x${string}`,
            publicClient,
            addLog,
            onSuccess: async receipt => {
              addLog(`✅ Batch confirmed in block ${receipt.blockNumber}!`);
              addLog(`🎉 Added ${amounts.reduce((a, b) => a + b, 0)} points total!`);
              await loadPoints();
            },
            onReverted: () => addLog("❌ Batch reverted on-chain"),
            onUnknown: async receipt => {
              addLog(`⚠️ Unknown receipt status: ${receipt.status}`);
              await loadPoints();
            },
          });
          if (!confirmed2) {
            addLog("⚠️ Confirmation timeout - batch may still be processing");
            addLog(`Check: https://explorer.testnet.rootstock.io/tx/${response.txHash}`);
            addTimer(() => loadPoints(), 3000);
          }
        }
      } else {
        addLog(`❌ Relayer error: ${response.error}`);
      }
    } catch (error: unknown) {
      addLog(`❌ Error: ${errorMessage(error)}`);
    } finally {
      finishAction("batch");
    }
  }, [address, walletClient, publicClient, addLog, addTimer, logEip712Payload, startAction, finishAction, loadPoints]);

  const clearLogs = useCallback(() => {
    setLogs([]);
    // Don't clear txHash — keep the last transaction hash visible.
  }, []);

  return {
    points,
    loadingPoints,
    loadPoints,
    logs,
    txHash,
    clearLogs,
    isRunning,
    handleDirectCall,
    handleGaslessCall,
    handleBatchCall,
  };
}
